version: "3.9"

services:
  app:
    image: bytecom/4us.dev
    environment:
      - TZ=America/Fortaleza
      - NEXT_PUBLIC_APP_ENV=production
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 5s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`app1.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - net_app

networks:
  net_app:
    external: true
