version: "3.9"

services:
  app:
    build: .
    environment:
      - TZ=America/Fortaleza
      - NEXT_PUBLIC_APP_ENV=production
    # ports:
    #   - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`app1.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - net_app

networks:
  net_app:
    external: true