version: "3.9"

services:
  app:
    image: bytecom/4us.dev
    environment:
      - TZ=America/Fortaleza
      - NEXT_PUBLIC_APP_ENV=production
    deploy:
      update_config:
        parallelism: 1
        delay: 3s
      restart_policy:
        condition: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`app1.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - net_app

networks:
  net_app:
    external: true
